wandb: True
save_weights: True
epochs: 100
net: "net.yaml"
learning_rate: 0.0001
weight_decay: 0.0001
early_stopping: True
patience: 10
batch_size: 100
difficulty: Easy
# These parameters allow training with a subset of sequences
# Commenting makes sure all data is used
#n_train: 10
#n_test: 2
#max_sequence_size: 2
# Percentage of train set used for validation
val_ratio: 0.2
