wandb: False
save_weights: True
epochs: 50
net: "net.yaml"
learning_rate: 0.01
weight_decay: 0
batch_size: 100
difficulty: Easy
# These parameters allow training with a subset of sequences
# Commenting makes sure all data is used
#n_train: 20
#n_test: 2
max_sequence_size: 5
